config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :users do
    resources :wishes
  end

  resource :session, only: [:destroy]
  get '/sessions/callback', to: "sessions#callback"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wishes
  accepts_nested_attributes_for :wishes, allow_destroy: true
  validates_presence_of :name, :last_name, :token
end

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :venue_name, :venue_photo, :user_id
  validates_uniqueness_of :venue_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
require 'foursquare'

class SessionsController < ApplicationController
  def callback
    callback_url = Foursquare.get_response("https://foursquare.com/oauth2/access_token?client_id=#{Rails.application.secrets['client_id']}&client_secret=#{Rails.application.secrets['client_secret']}&grant_type=authorization_code&redirect_uri=http://localhost:3000/sessions/callback&code=#{params[:code]}")
    @token = Foursquare.get_token(callback_url)
    api_response = Foursquare.json_parse("https://api.foursquare.com/v2/users/self?oauth_token=#{@token}&v=20140525")

    authenticate_or_authorize_user(api_response)
  end

  def destroy
    session[:user_id] = nil
    Rails.cache.delete("checkins")
    redirect_to root_path
    flash[:success] = t("session.signout")
  end

  private
  def authenticate_or_authorize_user(resp)
    user = User.where(token: @token).take

    if user
      sign_in(user)
    else
      sign_up(resp, @token)
    end
  end

  def sign_in(user)
    session[:user_id] = user.id
    current_user
    redirect_to user_wishes_path(user.id)
    flash[:success] = t("session.signin")
  end

  def sign_up(resp, token)
    user = User.new
    user.name = resp["response"]["user"]["firstName"]
    user.last_name =  resp["response"]["user"]["lastName"]
    user.token = token
    user.photo = "#{resp["response"]["user"]["photo"]["prefix"]}300x300#{resp["response"]["user"]["photo"]["suffix"]}"
    user.save

    sign_in user
  end
end

app/controllers/wishes_controller.rb
require 'foursquare'

class WishesController < ApplicationController
  def index
    @checkins ||= Foursquare.checkins(current_user.token)
    @wishes = Wish.where(user_id: current_user.id)
  end

  def create
    @wish = Wish.new(wish_params)
    if @wish.save
      redirect_to user_wishes_path
      flash[:success] = t("wish.add")
    else
      redirect_to user_wishes_path
      flash[:warning] = t("wish.exists")
    end
  end

  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy
    redirect_to user_wishes_path
    flash[:success] = t("wish.del")
  end

  private
  def wish_params
    params.require(:wish).permit(:venue_name, :venue_photo, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="bg">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wishlister</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <h3>Wishlister</h3>
        </div>
        <div class="col-lg-6">
          <div class="text-right user-info">
            <% unless current_user %>
              <%= link_to image_tag("connect-blue.png", class: "foursquare-signin"), "http://foursquare.com/oauth2/authenticate?client_id=#{Rails.application.secrets['client_id']}&response_type=code&redirect_uri=http://localhost:3000/sessions/callback", id: "login_foursquare" %>
            <% else %>
              <%= image_tag current_user.photo, class: "img-rounded", width: 50 %>
              <p><%= "#{current_user.name} #{current_user.last_name}" %><br/><%= link_to "Sair", session_path, method: :delete %></p>
            <% end %>
          </div>
        </div>
      </div>
      <% flash.each do |key, f| %>
        <div class="alert alert-<%= key %>">
          <%= f %>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/wishes/index.html.erb
<% if @wishes.count > 0 %>
  <h4>Wishlist</h4>
  <% @wishes.each do |wish| %>
    <ul class="wrapper" id="wish">
      <li class="photo-container">
        <%= image_tag wish.venue_photo, class: "img-rounded venue", width: 170 %>
      </li>
      <span><%= link_to "X", user_wish_path(current_user.id, wish), method: :delete, data: { confirm: "Deseja remover esse sonho?" }, class: "btn btn-danger btn-xs" %> <%= truncate(wish.venue_name, length: 20) %></span>
    </ul>
  <% end %>
<% end %>

<h4>Recent</h4>
<% @checkins.each do |id, checkin| %>
  <ul class="wrapper">
    <li class="photo-container">
      <%= image_tag checkin[:user_photo], class: "img-circle user", width: 50 %>
      <%= image_tag checkin[:venue_photo], class: "img-rounded venue", width: 170 %>
    </li>
    <span><%= link_to "+", user_wishes_path(wish: { venue_name: checkin[:venue_name], venue_photo: checkin[:venue_photo], user_id: current_user.id}), method: :post, class: "btn btn-success btn-xs" %> <%= truncate(checkin[:venue_name], length: 20) %></span>
  </ul>
<% end %>